args = None

CIFAR10Opt = {
    "name": "cifar10",
    "batch_size": 128,
    "learning_rate": 0.1,  # initial learning rate
    "weight_decay": 0.0005,
    "momentum": 0.9,
    "img_size": 3072,
    "file_path": "./dataset/CIFAR-10-C",
    "classes": [
        "airplane",
        "automobile",
        "bird",
        "cat",
        "deer",
        "dog",
        "frog",
        "horse",
        "ship",
        "truck",
    ],
    "num_class": 10,
    "severity": 5,
    "src_domains": ["original"],
    "tgt_domains": [
        "gaussian_noise-5",
        "shot_noise-5",
        "impulse_noise-5",
        "defocus_blur-5",
        "glass_blur-5",
        "motion_blur-5",
        "zoom_blur-5",
        "snow-5",
        "frost-5",
        "fog-5",
        "brightness-5",
        "contrast-5",
        "elastic_transform-5",
        "pixelate-5",
        "jpeg_compression-5",
    ],
}

CIFAR100Opt = {
    "name": "cifar100",
    "batch_size": 128,
    "learning_rate": 0.1,  # initial learning rate
    "weight_decay": 0.0005,
    "momentum": 0.9,
    "img_size": 3072,
    "file_path": "./dataset/CIFAR-100-C",
    "classes": [
        "beaver",
        "dolphin",
        "otter",
        "seal",
        "whale",
        "aquarium fish",
        "flatfish",
        "ray",
        "shark",
        "trout",
        "orchids",
        "poppies",
        "roses",
        "sunflowers",
        "tulips",
        "bottles",
        "bowls",
        "cans",
        "cups",
        "plates",
        "apples",
        "mushrooms",
        "oranges",
        "pears",
        "sweet peppers",
        "clock",
        "computer keyboard",
        "lamp",
        "telephone",
        "television",
        "bed",
        "chair",
        "couch",
        "table",
        "wardrobe",
        "bee",
        "beetle",
        "butterfly",
        "caterpillar",
        "cockroach",
        "bear",
        "leopard",
        "lion",
        "tiger",
        "wolf",
        "bridge",
        "castle",
        "house",
        "road",
        "skyscraper",
        "cloud",
        "forest",
        "mountain",
        "plain",
        "sea",
        "camel",
        "cattle",
        "chimpanzee",
        "elephant",
        "kangaroo",
        "fox",
        "porcupine",
        "possum",
        "raccoon",
        "skunk",
        "crab",
        "lobster",
        "snail",
        "spider",
        "worm",
        "baby",
        "boy",
        "girl",
        "man",
        "woman",
        "crocodile",
        "dinosaur",
        "lizard",
        "snake",
        "turtle",
        "hamster",
        "mouse",
        "rabbit",
        "shrew",
        "squirrel",
        "maple",
        "oak",
        "palm",
        "pine",
        "willow",
        "bicycle",
        "bus",
        "motorcycle",
        "pickup truck",
        "train",
        "lawn-mower",
        "rocket",
        "streetcar",
        "tank",
        "tractor",
    ],
    "num_class": 100,
    "severity": 5,
    "src_domains": ["original"],
    "tgt_domains": [
        "gaussian_noise-5",
        "shot_noise-5",
        "impulse_noise-5",
        "defocus_blur-5",
        "glass_blur-5",
        "motion_blur-5",
        "zoom_blur-5",
        "snow-5",
        "frost-5",
        "fog-5",
        "brightness-5",
        "contrast-5",
        "elastic_transform-5",
        "pixelate-5",
        "jpeg_compression-5",
    ],
}
